site_name: Zoom Online Manual
nav:
  - Getting Started: getting-started.md
  - Home: home.md
  - Chat: chat.md
  - Meetings: meetings.md
  - Contacts: contacts.md
  - Settings: settings.md
theme: readthedocs

